name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build, Test, Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Resolver dependências
        run: mvn dependency:go-offline

      - name: Compilar aplicação
        run: mvn compile

      - name: Executar testes
        run: mvn test

      - name: Build Docker image (sem push)
        run: docker build -t arkbank-ci .

  tag-release:
      name: Create Git Tag
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: write

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create and Push Git Tag
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag build-${{ github.run_number }}
            git push origin build-${{ github.run_number }}